export const CREATE_BOARD = "CREATE_BOARD";
export const CHANGE_CELL_STATE = "CHANGE_CELL_STATE";
export const CHANGE_GENERATION = "CHANGE_GENERATION";
export const CLEAR_BOARD = "CLEAR_BOARD";
export const RANDOMIZE_BOARD = "RANDOMIZE_BOARD";
